default: &default
  oauth_provider_client_id: <%= ENV["OAUTH_PVDR_CLID"] %>
  oauth_provider_client_secret: <%= ENV["OAUTH_PVDR_CLSC"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: db734a983db5374afe377778534b7bf1c5d232e637146087a0499c950ca5137dda313586bfce7b6390034088226a560787d11b3a083f77a667a9d53431be798d

dev:
  <<: *default

qa:
  <<: *default

production:
  <<: *default
